repository:
  name: SmartTripPlanner
  description: "SmartTripPlanner iOS app"
  private: false
  default_branch: main

branches:
  - name: main
    protection:
      required_status_checks:
        strict: true
        contexts:
          - "CI / Build and Test"
          - "CodeQL / CodeQL Analysis"
      enforce_admins: true
      required_pull_request_reviews:
        required_approving_review_count: 1
        require_code_owner_review: true
      required_linear_history: true
      allow_force_pushes: false
      allow_deletions: false
      block_creations: true

  - name: develop
    protection:
      required_status_checks:
        strict: false
        contexts:
          - "CI / Build and Test"
      enforce_admins: false
      required_pull_request_reviews:
        required_approving_review_count: 1
      allow_force_pushes: false
      allow_deletions: false
