disabled_rules:
  - trailing_whitespace
  - line_length

opt_in_rules:
  - empty_count
  - empty_string
  - explicit_init
  - force_unwrapping
  - closure_spacing
  - operator_usage_whitespace

excluded:
  - .build
  - Pods
  - vendor
  - fastlane

line_length:
  warning: 120
  error: 200
  ignores_function_declarations: true
  ignores_comments: true
  ignores_urls: true

file_length:
  warning: 500
  error: 1200

type_body_length:
  warning: 300
  error: 500

function_body_length:
  warning: 60
  error: 100

type_name:
  min_length: 3
  max_length: 40

identifier_name:
  min_length: 2
  max_length: 40
  excluded:
    - id
    - i
    - x
    - y
    - z

reporter: "xcode"
