blank_issues_enabled: false
contact_links:
  - name: Security vulnerability
    url: https://github.com/SmartTripPlanner/SmartTripPlanner/security/advisories/new
    about: Please report security vulnerabilities privately using GitHub's security advisory workflow.
