name: CI

on:
  pull_request:
    branches: [ main, develop ]
  push:
    branches: [ main ]

jobs:
  build-and-test:
    name: Build and Test
    runs-on: macos-14
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Select Xcode version
      run: sudo xcode-select -s /Applications/Xcode_15.2.app/Contents/Developer
    
    - name: Show Xcode version
      run: xcodebuild -version
    
    - name: Cache Swift Package Manager
      uses: actions/cache@v3
      with:
        path: |
          ~/Library/Developer/Xcode/DerivedData/**/SourcePackages
          SmartTripPlanner/SmartTripPlanner.xcodeproj/project.xcworkspace/xcshareddata/swiftpm
        key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-spm-
    
    - name: Install SwiftLint
      run: |
        brew install swiftlint
    
    - name: Install SwiftFormat
      run: |
        brew install swiftformat
    
    - name: Run SwiftLint
      run: |
        cd SmartTripPlanner
        swiftlint lint --strict
      continue-on-error: true
    
    - name: Run SwiftFormat (Check only)
      run: |
        cd SmartTripPlanner
        swiftformat --lint .
      continue-on-error: true
    
    - name: Build app
      run: |
        cd SmartTripPlanner
        xcodebuild clean build \
          -project SmartTripPlanner.xcodeproj \
          -scheme SmartTripPlanner \
          -destination 'platform=iOS Simulator,name=iPhone 15 Pro,OS=17.2' \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO
    
    - name: Run unit tests
      run: |
        cd SmartTripPlanner
        xcodebuild test \
          -project SmartTripPlanner.xcodeproj \
          -scheme SmartTripPlanner \
          -destination 'platform=iOS Simulator,name=iPhone 15 Pro,OS=17.2' \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO
